# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('teaser', models.TextField(max_length=1024)),
                ('order', models.IntegerField()),
                ('text', models.TextField(help_text='Story text - in Markdown. Appears before block structure.')),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name='story',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
