# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180406_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.CharField(default=projects.models.pkgen, max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, help_text='Block interpreted text - used only in HTML and Markdown blocks.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, help_text='Story audio - upload as MP3.', null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='story',
            name='teaser_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Image that appears on project page in designs.'),
        ),
        migrations.AddField(
            model_name='block',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Story'),
        ),
    ]
