# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180409_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['order', 'slug'], 'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.IntegerField(default=0, help_text='Priority of display on story page - lowest first.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='teaser_image',
            field=models.ImageField(blank=True, help_text='Image that appears on project page in designs.', null=True, upload_to=b''),
        ),
    ]
