# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180410_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text/md', 'Markdown Formatted Text'), ('text/html', 'HTML Formatted Text'), ('text/plain|h2', 'Large Heading'), ('text/plain|h3', 'Small Heading'), ('image/*|full', 'Full Width Image'), ('image/*|contain', 'Text Width Image'), ('audio/mpeg|play', 'MP3 Audio Player')], default='text/md', help_text='Choose what this block will do, then use those settings in the expanding menus below.', max_length=64, verbose_name='Block Type'),
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.CharField(default=projects.models.pkgen, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Internal CMS ID'),
        ),
        migrations.AlterField(
            model_name='block',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, help_text='Story text - in Markdown. Appears before block structure.'),
        ),
    ]
